/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Modelo;

/**
 *
 * @author vicente
 */
public class CRUD extends javax.swing.JFrame {

    /**
     * Creates new form CRUD
     */
    public CRUD() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        myPanel = new javax.swing.JPanel();
        panelTablas = new javax.swing.JPanel();
        btnItems = new javax.swing.JButton();
        btnCategorias = new javax.swing.JButton();
        btnMesas = new javax.swing.JButton();
        btnUsuarios = new javax.swing.JButton();
        panelCRUD = new javax.swing.JLayeredPane();
        panelItems = new javax.swing.JTabbedPane();
        panelCrearItem = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstVerCrearItem = new javax.swing.JList<>();
        lblResualtadoCrearUsuario = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtCrearNombre = new javax.swing.JTextField();
        txtCrearPrecio = new javax.swing.JTextField();
        chbCrearCategoria = new javax.swing.JComboBox<>();
        btnBuscarCrearImagen = new javax.swing.JButton();
        lblRutaImagen = new javax.swing.JLabel();
        txtCrearDescripcion = new javax.swing.JTextField();
        btnCrearItem = new javax.swing.JButton();
        panelModificarItem = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstVerModificarItem = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtModificarNombre = new javax.swing.JTextField();
        txtModificarPrecio = new javax.swing.JTextField();
        cbxModificarCategoria = new javax.swing.JComboBox<>();
        btnBuscarModificarImagen = new javax.swing.JButton();
        lblRutaBuscarImagen = new javax.swing.JLabel();
        txtModificarDescripcion = new javax.swing.JTextField();
        btnModificarItem = new javax.swing.JButton();
        panelEliminarItem = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnEliminarItem = new javax.swing.JButton();
        panelCategorias = new javax.swing.JTabbedPane();
        panelCrearCategoria = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        lstVerCrearCategoria = new javax.swing.JList<>();
        jLabel15 = new javax.swing.JLabel();
        txtCrearCategoria = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        lblResultadoCrearCategoria = new javax.swing.JLabel();
        panelModificarCategoria = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        lstVerModificarCategoria = new javax.swing.JList<>();
        jLabel17 = new javax.swing.JLabel();
        txtModificarCategoria = new javax.swing.JTextField();
        btnModificarCategoria = new javax.swing.JButton();
        lblResultadoModificarCategoria = new javax.swing.JLabel();
        panelEliminarCategoria = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        lstVerEliminarCategoria = new javax.swing.JList<>();
        lblCategoria = new javax.swing.JLabel();
        btnEliminarCategoria = new javax.swing.JButton();
        panelMesas = new javax.swing.JTabbedPane();
        panelCrearMesa = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        lstVerCrearMesas = new javax.swing.JList<>();
        btnCrearMesa = new javax.swing.JButton();
        lblResultadoCrearMesa = new javax.swing.JLabel();
        panelEliminarMesa = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        lstVerEliminarMesas = new javax.swing.JList<>();
        btnEliminarMesa = new javax.swing.JButton();
        lblResultadoEliminarMesa = new javax.swing.JLabel();
        panelUsuarios = new javax.swing.JTabbedPane();
        panelCrearUsuarios = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        lstVerCrearUsuarios = new javax.swing.JList<>();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txtCrearUsuario = new javax.swing.JTextField();
        txtCrearClave = new javax.swing.JPasswordField();
        chbVerClaveCrearUsuario = new javax.swing.JCheckBox();
        btnCrearUsuario = new javax.swing.JButton();
        lblResultadoCrearUsuario = new javax.swing.JLabel();
        panelModificarUsuario = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jScrollPane10 = new javax.swing.JScrollPane();
        lstVerModificarUsuario = new javax.swing.JList<>();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        txtModificarUsuario = new javax.swing.JTextField();
        txtModificarClave = new javax.swing.JPasswordField();
        chbVerClaveModificarUsuario = new javax.swing.JCheckBox();
        btnModificarUsuario = new javax.swing.JButton();
        lblResultadoModificarUsuario = new javax.swing.JLabel();
        panelEliminarUsuario = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jScrollPane11 = new javax.swing.JScrollPane();
        lstVerEliminarUsuario = new javax.swing.JList<>();
        btnEliminarUsuario = new javax.swing.JButton();
        lblResultadoEliminarUsuario = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnItems.setText("Items");
        btnItems.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnItemsActionPerformed(evt);
            }
        });

        btnCategorias.setText("Categorias");
        btnCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCategoriasActionPerformed(evt);
            }
        });

        btnMesas.setText("Mesas");
        btnMesas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMesasActionPerformed(evt);
            }
        });

        btnUsuarios.setText("Usuarios");
        btnUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuariosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelTablasLayout = new javax.swing.GroupLayout(panelTablas);
        panelTablas.setLayout(panelTablasLayout);
        panelTablasLayout.setHorizontalGroup(
            panelTablasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTablasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTablasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnMesas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCategorias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnItems, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        panelTablasLayout.setVerticalGroup(
            panelTablasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTablasLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(btnItems, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(btnMesas, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        panelCRUD.setLayout(new java.awt.CardLayout());

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 48)); // NOI18N
        jLabel1.setText("Crear item");

        jScrollPane1.setViewportView(lstVerCrearItem);

        jLabel5.setText("Nombre");

        jLabel6.setText("Precio");

        jLabel7.setText("Categoria");

        jLabel8.setText("Imagen");

        jLabel9.setText("Descripcion");

        btnBuscarCrearImagen.setText("Buscar");

        lblRutaImagen.setText("jLabel10");

        btnCrearItem.setText("Crear Item");

        javax.swing.GroupLayout panelCrearItemLayout = new javax.swing.GroupLayout(panelCrearItem);
        panelCrearItem.setLayout(panelCrearItemLayout);
        panelCrearItemLayout.setHorizontalGroup(
            panelCrearItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCrearItemLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCrearItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCrearItemLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtCrearNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelCrearItemLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtCrearPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCrearItemLayout.createSequentialGroup()
                        .addGroup(panelCrearItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                        .addGroup(panelCrearItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panelCrearItemLayout.createSequentialGroup()
                                .addComponent(lblRutaImagen)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnBuscarCrearImagen))
                            .addComponent(chbCrearCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel9)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCrearItemLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblResualtadoCrearUsuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelCrearItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnCrearItem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                            .addComponent(txtCrearDescripcion, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
            .addGroup(panelCrearItemLayout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelCrearItemLayout.setVerticalGroup(
            panelCrearItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCrearItemLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(panelCrearItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCrearItemLayout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(lblResualtadoCrearUsuario)
                        .addContainerGap(133, Short.MAX_VALUE))
                    .addGroup(panelCrearItemLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelCrearItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelCrearItemLayout.createSequentialGroup()
                                .addGroup(panelCrearItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(txtCrearNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(panelCrearItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(txtCrearPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(2, 2, 2)
                                .addGroup(panelCrearItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(chbCrearCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(panelCrearItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(btnBuscarCrearImagen)
                                    .addComponent(lblRutaImagen))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(panelCrearItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(txtCrearDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnCrearItem)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane1))
                        .addContainerGap())))
        );

        panelItems.addTab("Crear", panelCrearItem);

        jLabel4.setFont(new java.awt.Font("Ubuntu", 1, 48)); // NOI18N
        jLabel4.setText("Modificar item");

        jScrollPane2.setViewportView(lstVerModificarItem);

        jLabel2.setText("Nombre");

        jLabel3.setText("Precio");

        jLabel10.setText("Categoria");

        jLabel11.setText("Imagen");

        jLabel12.setText("Descripcion");

        cbxModificarCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));

        btnBuscarModificarImagen.setText("Buscar");

        lblRutaBuscarImagen.setText("jLabel13");

        btnModificarItem.setText("Modificar item");

        javax.swing.GroupLayout panelModificarItemLayout = new javax.swing.GroupLayout(panelModificarItem);
        panelModificarItem.setLayout(panelModificarItemLayout);
        panelModificarItemLayout.setHorizontalGroup(
            panelModificarItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelModificarItemLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelModificarItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelModificarItemLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtModificarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelModificarItemLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtModificarPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelModificarItemLayout.createSequentialGroup()
                        .addGroup(panelModificarItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelModificarItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnModificarItem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                            .addComponent(txtModificarDescripcion)
                            .addGroup(panelModificarItemLayout.createSequentialGroup()
                                .addComponent(lblRutaBuscarImagen)
                                .addGap(66, 66, 66)
                                .addComponent(btnBuscarModificarImagen))
                            .addComponent(cbxModificarCategoria, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelModificarItemLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(62, 62, 62))
        );
        panelModificarItemLayout.setVerticalGroup(
            panelModificarItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelModificarItemLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelModificarItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(panelModificarItemLayout.createSequentialGroup()
                        .addGroup(panelModificarItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtModificarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(panelModificarItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtModificarPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelModificarItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(cbxModificarCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelModificarItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(btnBuscarModificarImagen)
                            .addComponent(lblRutaBuscarImagen))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelModificarItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(txtModificarDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnModificarItem)
                        .addGap(0, 43, Short.MAX_VALUE)))
                .addContainerGap())
        );

        panelItems.addTab("Modificar", panelModificarItem);

        jLabel13.setFont(new java.awt.Font("Ubuntu", 1, 48)); // NOI18N
        jLabel13.setText("Eliminar item");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTable1);

        btnEliminarItem.setText("Eliminar item");

        javax.swing.GroupLayout panelEliminarItemLayout = new javax.swing.GroupLayout(panelEliminarItem);
        panelEliminarItem.setLayout(panelEliminarItemLayout);
        panelEliminarItemLayout.setHorizontalGroup(
            panelEliminarItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEliminarItemLayout.createSequentialGroup()
                .addGroup(panelEliminarItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelEliminarItemLayout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(jLabel13)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEliminarItemLayout.createSequentialGroup()
                        .addGap(0, 69, Short.MAX_VALUE)
                        .addGroup(panelEliminarItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane4)
                            .addComponent(btnEliminarItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        panelEliminarItemLayout.setVerticalGroup(
            panelEliminarItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEliminarItemLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEliminarItem)
                .addGap(240, 240, 240))
        );

        panelItems.addTab("Eliminar", panelEliminarItem);

        panelCRUD.add(panelItems, "card2");

        jLabel14.setFont(new java.awt.Font("Ubuntu", 1, 48)); // NOI18N
        jLabel14.setText("Crear categoria");

        lstVerCrearCategoria.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(lstVerCrearCategoria);

        jLabel15.setText("Categoria");

        jButton1.setText("Crear categoria");

        javax.swing.GroupLayout panelCrearCategoriaLayout = new javax.swing.GroupLayout(panelCrearCategoria);
        panelCrearCategoria.setLayout(panelCrearCategoriaLayout);
        panelCrearCategoriaLayout.setHorizontalGroup(
            panelCrearCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCrearCategoriaLayout.createSequentialGroup()
                .addContainerGap(119, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addGap(61, 61, 61))
            .addGroup(panelCrearCategoriaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCrearCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCrearCategoriaLayout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(18, 18, 18)
                        .addGroup(panelCrearCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCrearCategoria)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCrearCategoriaLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblResultadoCrearCategoria)))
                .addContainerGap())
        );
        panelCrearCategoriaLayout.setVerticalGroup(
            panelCrearCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCrearCategoriaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCrearCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                    .addGroup(panelCrearCategoriaLayout.createSequentialGroup()
                        .addGroup(panelCrearCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(txtCrearCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblResultadoCrearCategoria)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        panelCategorias.addTab("Crear", panelCrearCategoria);

        jLabel16.setFont(new java.awt.Font("Ubuntu", 1, 48)); // NOI18N
        jLabel16.setText("Modificar categoria");

        jScrollPane5.setViewportView(lstVerModificarCategoria);

        jLabel17.setText("Categoria");

        btnModificarCategoria.setText("Modificar Categoria");

        javax.swing.GroupLayout panelModificarCategoriaLayout = new javax.swing.GroupLayout(panelModificarCategoria);
        panelModificarCategoria.setLayout(panelModificarCategoriaLayout);
        panelModificarCategoriaLayout.setHorizontalGroup(
            panelModificarCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelModificarCategoriaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelModificarCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelModificarCategoriaLayout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(18, 18, 18)
                        .addGroup(panelModificarCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtModificarCategoria)
                            .addComponent(btnModificarCategoria, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelModificarCategoriaLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblResultadoModificarCategoria)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelModificarCategoriaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addGap(43, 43, 43))
        );
        panelModificarCategoriaLayout.setVerticalGroup(
            panelModificarCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelModificarCategoriaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelModificarCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                    .addGroup(panelModificarCategoriaLayout.createSequentialGroup()
                        .addGroup(panelModificarCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(txtModificarCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnModificarCategoria)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblResultadoModificarCategoria)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        panelCategorias.addTab("Modificar", panelModificarCategoria);

        jLabel18.setFont(new java.awt.Font("Ubuntu", 1, 48)); // NOI18N
        jLabel18.setText("Eliminar Categoria");

        jScrollPane7.setViewportView(lstVerEliminarCategoria);

        btnEliminarCategoria.setText("Eliminar categoria");

        javax.swing.GroupLayout panelEliminarCategoriaLayout = new javax.swing.GroupLayout(panelEliminarCategoria);
        panelEliminarCategoria.setLayout(panelEliminarCategoriaLayout);
        panelEliminarCategoriaLayout.setHorizontalGroup(
            panelEliminarCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEliminarCategoriaLayout.createSequentialGroup()
                .addGroup(panelEliminarCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelEliminarCategoriaLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jLabel18))
                    .addGroup(panelEliminarCategoriaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(panelEliminarCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelEliminarCategoriaLayout.createSequentialGroup()
                                .addComponent(lblCategoria)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(btnEliminarCategoria, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE))))
                .addContainerGap())
        );
        panelEliminarCategoriaLayout.setVerticalGroup(
            panelEliminarCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEliminarCategoriaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelEliminarCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                    .addGroup(panelEliminarCategoriaLayout.createSequentialGroup()
                        .addComponent(lblCategoria)
                        .addGap(37, 37, 37)
                        .addComponent(btnEliminarCategoria)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        panelCategorias.addTab("Eliminar", panelEliminarCategoria);

        panelCRUD.add(panelCategorias, "card3");

        jLabel19.setFont(new java.awt.Font("Ubuntu", 1, 48)); // NOI18N
        jLabel19.setText("Crear mesas");

        jScrollPane6.setViewportView(lstVerCrearMesas);

        btnCrearMesa.setText("Agregar mesa");

        javax.swing.GroupLayout panelCrearMesaLayout = new javax.swing.GroupLayout(panelCrearMesa);
        panelCrearMesa.setLayout(panelCrearMesaLayout);
        panelCrearMesaLayout.setHorizontalGroup(
            panelCrearMesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCrearMesaLayout.createSequentialGroup()
                .addGroup(panelCrearMesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCrearMesaLayout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(jLabel19)
                        .addGap(0, 119, Short.MAX_VALUE))
                    .addGroup(panelCrearMesaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(panelCrearMesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCrearMesa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCrearMesaLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(lblResultadoCrearMesa)))))
                .addContainerGap())
        );
        panelCrearMesaLayout.setVerticalGroup(
            panelCrearMesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCrearMesaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCrearMesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                    .addGroup(panelCrearMesaLayout.createSequentialGroup()
                        .addComponent(btnCrearMesa)
                        .addGap(18, 18, 18)
                        .addComponent(lblResultadoCrearMesa)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        panelMesas.addTab("Crear", panelCrearMesa);

        jLabel20.setFont(new java.awt.Font("Ubuntu", 1, 48)); // NOI18N
        jLabel20.setText("Eliminar mesas");

        jScrollPane8.setViewportView(lstVerEliminarMesas);

        btnEliminarMesa.setText("Eliminar mesa");

        javax.swing.GroupLayout panelEliminarMesaLayout = new javax.swing.GroupLayout(panelEliminarMesa);
        panelEliminarMesa.setLayout(panelEliminarMesaLayout);
        panelEliminarMesaLayout.setHorizontalGroup(
            panelEliminarMesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEliminarMesaLayout.createSequentialGroup()
                .addGroup(panelEliminarMesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelEliminarMesaLayout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(jLabel20)
                        .addGap(0, 88, Short.MAX_VALUE))
                    .addGroup(panelEliminarMesaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelEliminarMesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnEliminarMesa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEliminarMesaLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(lblResultadoEliminarMesa)))))
                .addContainerGap())
        );
        panelEliminarMesaLayout.setVerticalGroup(
            panelEliminarMesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEliminarMesaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelEliminarMesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                    .addGroup(panelEliminarMesaLayout.createSequentialGroup()
                        .addComponent(btnEliminarMesa)
                        .addGap(18, 18, 18)
                        .addComponent(lblResultadoEliminarMesa)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        panelMesas.addTab("Eliminar", panelEliminarMesa);

        panelCRUD.add(panelMesas, "card4");

        jLabel21.setFont(new java.awt.Font("Ubuntu", 1, 48)); // NOI18N
        jLabel21.setText("Crear usuario");

        jScrollPane9.setViewportView(lstVerCrearUsuarios);

        jLabel22.setText("Nombre");

        jLabel23.setText("Clave");

        chbVerClaveCrearUsuario.setText("Ver clave");

        btnCrearUsuario.setText("Crear usuario");

        javax.swing.GroupLayout panelCrearUsuariosLayout = new javax.swing.GroupLayout(panelCrearUsuarios);
        panelCrearUsuarios.setLayout(panelCrearUsuariosLayout);
        panelCrearUsuariosLayout.setHorizontalGroup(
            panelCrearUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCrearUsuariosLayout.createSequentialGroup()
                .addGroup(panelCrearUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCrearUsuariosLayout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(jLabel21))
                    .addGroup(panelCrearUsuariosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelCrearUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelCrearUsuariosLayout.createSequentialGroup()
                                .addGroup(panelCrearUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel22)
                                    .addComponent(jLabel23))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                                .addGroup(panelCrearUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtCrearClave)
                                    .addComponent(txtCrearUsuario)
                                    .addComponent(chbVerClaveCrearUsuario)
                                    .addComponent(btnCrearUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCrearUsuariosLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(lblResultadoCrearUsuario)))))
                .addContainerGap())
        );
        panelCrearUsuariosLayout.setVerticalGroup(
            panelCrearUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCrearUsuariosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCrearUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane9)
                    .addGroup(panelCrearUsuariosLayout.createSequentialGroup()
                        .addGroup(panelCrearUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(txtCrearUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelCrearUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(txtCrearClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chbVerClaveCrearUsuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCrearUsuario)
                        .addGap(18, 18, 18)
                        .addComponent(lblResultadoCrearUsuario)
                        .addGap(0, 111, Short.MAX_VALUE)))
                .addContainerGap())
        );

        panelUsuarios.addTab("Crear", panelCrearUsuarios);

        jLabel24.setFont(new java.awt.Font("Ubuntu", 1, 48)); // NOI18N
        jLabel24.setText("Modificar usuario");

        jScrollPane10.setViewportView(lstVerModificarUsuario);

        jLabel25.setText("Nombre");

        jLabel26.setText("Clave");

        chbVerClaveModificarUsuario.setText("Ver clave");

        btnModificarUsuario.setText("Modificar usuario");

        javax.swing.GroupLayout panelModificarUsuarioLayout = new javax.swing.GroupLayout(panelModificarUsuario);
        panelModificarUsuario.setLayout(panelModificarUsuarioLayout);
        panelModificarUsuarioLayout.setHorizontalGroup(
            panelModificarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelModificarUsuarioLayout.createSequentialGroup()
                .addContainerGap(72, Short.MAX_VALUE)
                .addComponent(jLabel24)
                .addGap(65, 65, 65))
            .addGroup(panelModificarUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelModificarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelModificarUsuarioLayout.createSequentialGroup()
                        .addGroup(panelModificarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel25)
                            .addComponent(jLabel26))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelModificarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtModificarClave)
                            .addComponent(txtModificarUsuario)
                            .addComponent(chbVerClaveModificarUsuario)
                            .addComponent(btnModificarUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelModificarUsuarioLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblResultadoModificarUsuario)))
                .addContainerGap())
        );
        panelModificarUsuarioLayout.setVerticalGroup(
            panelModificarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelModificarUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelModificarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane10)
                    .addGroup(panelModificarUsuarioLayout.createSequentialGroup()
                        .addGroup(panelModificarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel25)
                            .addComponent(txtModificarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelModificarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel26)
                            .addComponent(txtModificarClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chbVerClaveModificarUsuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnModificarUsuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblResultadoModificarUsuario)
                        .addGap(0, 117, Short.MAX_VALUE)))
                .addContainerGap())
        );

        panelUsuarios.addTab("Modificar", panelModificarUsuario);

        jLabel27.setFont(new java.awt.Font("Ubuntu", 1, 48)); // NOI18N
        jLabel27.setText("Eliminar usuario");

        jScrollPane11.setViewportView(lstVerEliminarUsuario);

        btnEliminarUsuario.setText("Eliminar Usuario");

        javax.swing.GroupLayout panelEliminarUsuarioLayout = new javax.swing.GroupLayout(panelEliminarUsuario);
        panelEliminarUsuario.setLayout(panelEliminarUsuarioLayout);
        panelEliminarUsuarioLayout.setHorizontalGroup(
            panelEliminarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEliminarUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelEliminarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelEliminarUsuarioLayout.createSequentialGroup()
                        .addGroup(panelEliminarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane11)
                            .addComponent(btnEliminarUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEliminarUsuarioLayout.createSequentialGroup()
                        .addGap(0, 74, Short.MAX_VALUE)
                        .addGroup(panelEliminarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEliminarUsuarioLayout.createSequentialGroup()
                                .addComponent(jLabel27)
                                .addGap(83, 83, 83))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEliminarUsuarioLayout.createSequentialGroup()
                                .addComponent(lblResultadoEliminarUsuario)
                                .addContainerGap())))))
        );
        panelEliminarUsuarioLayout.setVerticalGroup(
            panelEliminarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEliminarUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEliminarUsuario)
                .addGap(18, 18, 18)
                .addComponent(lblResultadoEliminarUsuario)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelUsuarios.addTab("Eliminar", panelEliminarUsuario);

        panelCRUD.add(panelUsuarios, "card5");

        javax.swing.GroupLayout myPanelLayout = new javax.swing.GroupLayout(myPanel);
        myPanel.setLayout(myPanelLayout);
        myPanelLayout.setHorizontalGroup(
            myPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(myPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelTablas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelCRUD)
                .addContainerGap())
        );
        myPanelLayout.setVerticalGroup(
            myPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(myPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(myPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelCRUD, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(panelTablas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(myPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(myPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnItemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnItemsActionPerformed
       panelCRUD.removeAll();
       panelCRUD.add(panelItems);
       panelCRUD.repaint();
       panelCRUD.revalidate();
    }//GEN-LAST:event_btnItemsActionPerformed

    private void btnCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCategoriasActionPerformed
       panelCRUD.removeAll();
       panelCRUD.add(panelCategorias);
       panelCRUD.repaint();
       panelCRUD.revalidate();
    }//GEN-LAST:event_btnCategoriasActionPerformed

    private void btnMesasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMesasActionPerformed
       panelCRUD.removeAll();
       panelCRUD.add(panelMesas);
       panelCRUD.repaint();
       panelCRUD.revalidate();
    }//GEN-LAST:event_btnMesasActionPerformed

    private void btnUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuariosActionPerformed
       panelCRUD.removeAll();
       panelCRUD.add(panelUsuarios);
       panelCRUD.repaint();
       panelCRUD.revalidate();
    }//GEN-LAST:event_btnUsuariosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CRUD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarCrearImagen;
    private javax.swing.JButton btnBuscarModificarImagen;
    private javax.swing.JButton btnCategorias;
    private javax.swing.JButton btnCrearItem;
    private javax.swing.JButton btnCrearMesa;
    private javax.swing.JButton btnCrearUsuario;
    private javax.swing.JButton btnEliminarCategoria;
    private javax.swing.JButton btnEliminarItem;
    private javax.swing.JButton btnEliminarMesa;
    private javax.swing.JButton btnEliminarUsuario;
    private javax.swing.JButton btnItems;
    private javax.swing.JButton btnMesas;
    private javax.swing.JButton btnModificarCategoria;
    private javax.swing.JButton btnModificarItem;
    private javax.swing.JButton btnModificarUsuario;
    private javax.swing.JButton btnUsuarios;
    private javax.swing.JComboBox<String> cbxModificarCategoria;
    private javax.swing.JComboBox<String> chbCrearCategoria;
    private javax.swing.JCheckBox chbVerClaveCrearUsuario;
    private javax.swing.JCheckBox chbVerClaveModificarUsuario;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblCategoria;
    private javax.swing.JLabel lblResualtadoCrearUsuario;
    private javax.swing.JLabel lblResultadoCrearCategoria;
    private javax.swing.JLabel lblResultadoCrearMesa;
    private javax.swing.JLabel lblResultadoCrearUsuario;
    private javax.swing.JLabel lblResultadoEliminarMesa;
    private javax.swing.JLabel lblResultadoEliminarUsuario;
    private javax.swing.JLabel lblResultadoModificarCategoria;
    private javax.swing.JLabel lblResultadoModificarUsuario;
    private javax.swing.JLabel lblRutaBuscarImagen;
    private javax.swing.JLabel lblRutaImagen;
    private javax.swing.JList<String> lstVerCrearCategoria;
    private javax.swing.JList<String> lstVerCrearItem;
    private javax.swing.JList<String> lstVerCrearMesas;
    private javax.swing.JList<String> lstVerCrearUsuarios;
    private javax.swing.JList<String> lstVerEliminarCategoria;
    private javax.swing.JList<String> lstVerEliminarMesas;
    private javax.swing.JList<String> lstVerEliminarUsuario;
    private javax.swing.JList<String> lstVerModificarCategoria;
    private javax.swing.JList<String> lstVerModificarItem;
    private javax.swing.JList<String> lstVerModificarUsuario;
    private javax.swing.JPanel myPanel;
    private javax.swing.JLayeredPane panelCRUD;
    private javax.swing.JTabbedPane panelCategorias;
    private javax.swing.JPanel panelCrearCategoria;
    private javax.swing.JPanel panelCrearItem;
    private javax.swing.JPanel panelCrearMesa;
    private javax.swing.JPanel panelCrearUsuarios;
    private javax.swing.JPanel panelEliminarCategoria;
    private javax.swing.JPanel panelEliminarItem;
    private javax.swing.JPanel panelEliminarMesa;
    private javax.swing.JPanel panelEliminarUsuario;
    private javax.swing.JTabbedPane panelItems;
    private javax.swing.JTabbedPane panelMesas;
    private javax.swing.JPanel panelModificarCategoria;
    private javax.swing.JPanel panelModificarItem;
    private javax.swing.JPanel panelModificarUsuario;
    private javax.swing.JPanel panelTablas;
    private javax.swing.JTabbedPane panelUsuarios;
    private javax.swing.JTextField txtCrearCategoria;
    private javax.swing.JPasswordField txtCrearClave;
    private javax.swing.JTextField txtCrearDescripcion;
    private javax.swing.JTextField txtCrearNombre;
    private javax.swing.JTextField txtCrearPrecio;
    private javax.swing.JTextField txtCrearUsuario;
    private javax.swing.JTextField txtModificarCategoria;
    private javax.swing.JPasswordField txtModificarClave;
    private javax.swing.JTextField txtModificarDescripcion;
    private javax.swing.JTextField txtModificarNombre;
    private javax.swing.JTextField txtModificarPrecio;
    private javax.swing.JTextField txtModificarUsuario;
    // End of variables declaration//GEN-END:variables
}
